import subprocess
print("---------------------")
p1 = subprocess.run('ls')
print("#####################")
p2 = subprocess.run(['ls','-l'])
print("#####################")
print(p1)
print(p1.returncode)
print(p1.stdout)
print(p1.args)
print("#####################")
p3 = subprocess.run('ls', capture_output=True)
print("#####################")
print(p3)
print(p3.returncode)
print(p3.stdout)
print(p3.args)
print("#####################")
print(p3.stdout.decode())
print("#####################")
p4 = subprocess.run('ls', capture_output=True, text = True)
print("#####################")
print(p4)
print(p4.returncode)
print(p4.stdout) # no need to decode
print(p4.args)
print("#####################")
